<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Empresa [
   <!ELEMENT Empresa (Empleado)>
   <!ELEMENT Empleado (Apellido, Nombre, Email, Telefono, Direccion)>
   <!ATTLIST Empleado NumEmpleado CDATA #REQUIRED>
   <!ELEMENT Apellido (#PCDATA)>
   <!ELEMENT Nombre (#PCDATA)>
   <!ELEMENT Email (#PCDATA)>
   <!ELEMENT Telefono (#PCDATA)>
   <!ELEMENT Direccion (#PCDATA)>
   <!ATTLIST Direccion Ciudad CDATA >
   <!ATTLIST Direccion Calle CDATA #REQUIRED>
   <!ATTLIST Direccion CP CDATA #REQUIRED>
]>

<Empresa>
  <Empleado NumEmpleado="1234567890">
    <Apellido>Perez</Apellido>
    <Nombre>Juan</Nombre>
    <Email>juanperez@gmail.com</Email>
    <Telefono>666 555 444</Telefono>
    <Direccion Ciudad="Barcelona" Calle="Carrer de Pau Claris, 121" CP="08009"></Direccion>  
  </Empleado>
</Empresa>
